import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=(s,r=document)=>r.querySelector(s);
const money=(v=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const dateBR=v=>v?new Intl.DateTimeFormat('pt-BR').format(new Date(`${v}T12:00:00`)):'Sem prazo';
let user=null,goals=[],editingId=null,contributionId=null,deletingId=null;
function toast(message,type='ok'){const el=$('#toast');if(!el)return;el.textContent=message;el.className=`toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3200)}
function esc(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function ensureStyles(){if(document.querySelector('link[data-goals-module]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./css/goals-module.css?v=20260913-0050';l.dataset.goalsModule='1';document.head.appendChild(l)}
function ensureUI(){const p=$('#goalsPage');if(!p)return;p.innerHTML=`<div class="goals-shell"><div class="goals-toolbar"><div><span class="eyebrow">OBJETIVOS</span><h2>Metas</h2><p>Transforme planos em objetivos mensuráveis e acompanhe o progresso.</p></div><button class="primary-btn" data-goal-new type="button">+ Nova meta</button></div><div class="goals-kpis"><article class="goal-kpi"><span>Total das metas</span><strong id="goalTotalTarget">R$ 0,00</strong><small>Objetivos cadastrados</small></article><article class="goal-kpi"><span>Já acumulado</span><strong id="goalTotalCurrent">R$ 0,00</strong><small>Progresso consolidado</small></article><article class="goal-kpi"><span>Falta alcançar</span><strong id="goalTotalRemaining">R$ 0,00</strong><small>Valor restante</small></article><article class="goal-kpi"><span>Metas concluídas</span><strong id="goalCompletedCount">0</strong><small>Objetivos atingidos</small></article></div><div id="goalsGrid" class="goals-grid"></div></div>`;
if($('#goalModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="goalModal" class="modal hidden" role="dialog" aria-modal="true"><div class="modal-backdrop" data-close-goal></div><div class="modal-card"><div class="modal-head"><div><span class="eyebrow">META FINANCEIRA</span><h2 id="goalModalTitle">Nova meta</h2></div><button class="icon-btn" data-close-goal type="button">×</button></div><form id="goalForm" class="goal-form"><label>Nome da meta<input id="goalName" required placeholder="Ex.: Reserva de emergência" /></label><div class="goal-modal-grid"><label>Valor-alvo<input id="goalTarget" type="number" min="0.01" step="0.01" inputmode="decimal" required /></label><label>Valor já acumulado<input id="goalCurrent" type="number" min="0" step="0.01" inputmode="decimal" value="0" required /></label></div><div class="goal-modal-grid"><label>Data-alvo<input id="goalDate" type="date" /></label><label>Status<select id="goalStatus"><option value="ativa">Ativa</option><option value="pausada">Pausada</option><option value="concluida">Concluída</option></select></label></div><div class="goal-modal-actions"><button class="ghost-btn" data-close-goal type="button">Cancelar</button><button id="saveGoalBtn" class="primary-btn" type="submit">Salvar meta</button></div></form></div></div><div id="goalContributionModal" class="modal hidden" role="dialog" aria-modal="true"><div class="modal-backdrop" data-close-goal-contribution></div><div class="modal-card"><div class="modal-head"><div><span class="eyebrow">PROGRESSO</span><h2>Adicionar valor à meta</h2></div><button class="icon-btn" data-close-goal-contribution type="button">×</button></div><form id="goalContributionForm" class="goal-contribution-form"><div id="goalContributionPreview" class="goal-confirm"></div><label>Valor a adicionar<input id="goalContributionAmount" type="number" min="0.01" step="0.01" inputmode="decimal" required /></label><div class="goal-modal-actions"><button class="ghost-btn" data-close-goal-contribution type="button">Cancelar</button><button class="primary-btn" type="submit">Adicionar valor</button></div></form></div></div><div id="goalDeleteModal" class="modal hidden" role="dialog" aria-modal="true"><div class="modal-backdrop" data-close-goal-delete></div><div class="modal-card"><div class="modal-head"><div><span class="eyebrow">CONFIRMAÇÃO</span><h2>Excluir meta?</h2></div><button class="icon-btn" data-close-goal-delete type="button">×</button></div><div id="goalDeletePreview" class="goal-confirm"></div><p>Esta ação remove apenas a meta, sem alterar lançamentos financeiros.</p><div class="goal-modal-actions"><button class="ghost-btn" data-close-goal-delete type="button">Cancelar</button><button id="confirmGoalDelete" class="danger-btn" type="button">Excluir meta</button></div></div></div>`)}
function daysText(date){if(!date)return'Sem prazo';const today=new Date();today.setHours(0,0,0,0);const end=new Date(`${date}T12:00:00`);const d=Math.ceil((end-today)/86400000);if(d<0)return`Prazo vencido há ${Math.abs(d)} dia(s)`;if(d===0)return'Prazo hoje';return`${d} dia(s) restantes`}
function render(){const host=$('#goalsGrid');if(!host)return;const totalTarget=goals.reduce((s,g)=>s+Number(g.target_amount||0),0),totalCurrent=goals.reduce((s,g)=>s+Number(g.current_amount||0),0),remaining=Math.max(0,totalTarget-totalCurrent),done=goals.filter(g=>g.status==='concluida').length;$('#goalTotalTarget').textContent=money(totalTarget);$('#goalTotalCurrent').textContent=money(totalCurrent);$('#goalTotalRemaining').textContent=money(remaining);$('#goalCompletedCount').textContent=String(done);if(!goals.length){host.innerHTML='<div class="goals-empty"><strong>Nenhuma meta cadastrada</strong><p>Crie sua primeira meta financeira para acompanhar o progresso.</p><button class="primary-btn" data-goal-new type="button">+ Criar meta</button></div>';return}host.innerHTML=goals.map(g=>{const target=Number(g.target_amount||0),current=Number(g.current_amount||0),pct=target>0?Math.min(100,Math.round(current/target*100)):0,remain=Math.max(0,target-current),overdue=g.target_date&&new Date(`${g.target_date}T12:00:00`)<new Date()&&g.status!=='concluida';return`<article class="goal-card"><div class="goal-head"><div><h3>${esc(g.name)}</h3><small class="${overdue?'goal-overdue':''}">${esc(daysText(g.target_date))} • ${dateBR(g.target_date)}</small></div><span class="goal-status ${g.status}">${g.status==='ativa'?'Ativa':g.status==='pausada'?'Pausada':'Concluída'}</span></div><div class="goal-progress"><i style="width:${pct}%"></i></div><div class="goal-values"><div><span>Meta</span><b>${money(target)}</b></div><div><span>Acumulado</span><b>${money(current)}</b></div><div><span>Falta</span><b>${money(remain)} • ${pct}%</b></div></div><div class="goal-actions"><button class="ghost-btn" data-goal-add="${g.id}" type="button">+ Valor</button><button class="ghost-btn" data-goal-edit="${g.id}" type="button">Editar</button><button class="ghost-btn" data-goal-toggle="${g.id}" type="button">${g.status==='pausada'?'Retomar':g.status==='ativa'?'Pausar':'Reabrir'}</button><button class="ghost-btn" data-goal-delete="${g.id}" type="button">Excluir</button></div></article>`}).join('')}
async function load(){if(!user)return;const {data,error}=await supabase.from('financial_goals').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(error)return toast(error.message,'error');goals=data||[];render()}
function openGoal(id=null){editingId=id;const g=id?goals.find(x=>x.id===id):null;$('#goalModalTitle').textContent=g?'Editar meta':'Nova meta';$('#goalName').value=g?.name||'';$('#goalTarget').value=g?Number(g.target_amount):'';$('#goalCurrent').value=g?Number(g.current_amount):0;$('#goalDate').value=g?.target_date||'';$('#goalStatus').value=g?.status||'ativa';$('#goalModal').classList.remove('hidden');document.body.classList.add('modal-open')}
function closeGoal(){editingId=null;$('#goalModal').classList.add('hidden');document.body.classList.remove('modal-open')}
async function saveGoal(e){e.preventDefault();if(!user)return;const target=Number($('#goalTarget').value),current=Number($('#goalCurrent').value),status=current>=target?'concluida':$('#goalStatus').value,payload={user_id:user.id,name:$('#goalName').value.trim(),target_amount:target,current_amount:current,target_date:$('#goalDate').value||null,status,updated_at:new Date().toISOString()};const b=$('#saveGoalBtn'),txt=b.textContent;b.disabled=true;b.textContent='Salvando...';let error;if(editingId)({error}=await supabase.from('financial_goals').update(payload).eq('id',editingId).eq('user_id',user.id));else({error}=await supabase.from('financial_goals').insert(payload));b.disabled=false;b.textContent=txt;if(error)return toast(error.message,'error');const wasEditing=Boolean(editingId);closeGoal();toast(wasEditing?'Meta atualizada.':'Meta criada.');await load()}
function openContribution(id){const g=goals.find(x=>x.id===id);if(!g)return;contributionId=id;$('#goalContributionPreview').innerHTML=`<span>${esc(g.name)}</span><b>${money(g.current_amount)} / ${money(g.target_amount)}</b>`;$('#goalContributionAmount').value='';$('#goalContributionModal').classList.remove('hidden');document.body.classList.add('modal-open')}
function closeContribution(){contributionId=null;$('#goalContributionModal').classList.add('hidden');document.body.classList.remove('modal-open')}
async function addContribution(e){e.preventDefault();const g=goals.find(x=>x.id===contributionId);if(!g)return;const add=Number($('#goalContributionAmount').value||0);if(add<=0)return toast('Informe um valor maior que zero.','error');const next=Number(g.current_amount||0)+add,status=next>=Number(g.target_amount||0)?'concluida':g.status==='concluida'?'ativa':g.status;const {error}=await supabase.from('financial_goals').update({current_amount:next,status,updated_at:new Date().toISOString()}).eq('id',g.id).eq('user_id',user.id);if(error)return toast(error.message,'error');closeContribution();toast(status==='concluida'?'Meta concluída! 🎯':'Valor adicionado à meta.');await load()}
async function toggleGoal(id){const g=goals.find(x=>x.id===id);if(!g)return;const status=g.status==='pausada'?'ativa':g.status==='ativa'?'pausada':'ativa';const {error}=await supabase.from('financial_goals').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id);if(error)return toast(error.message,'error');toast(status==='pausada'?'Meta pausada.':'Meta ativada.');await load()}
function openDelete(id){const g=goals.find(x=>x.id===id);if(!g)return;deletingId=id;$('#goalDeletePreview').innerHTML=`<span>${esc(g.name)}</span><b>${money(g.current_amount)} / ${money(g.target_amount)}</b>`;$('#goalDeleteModal').classList.remove('hidden');document.body.classList.add('modal-open')}
function closeDelete(){deletingId=null;$('#goalDeleteModal').classList.add('hidden');document.body.classList.remove('modal-open')}
async function confirmDelete(){if(!deletingId)return;const {error}=await supabase.from('financial_goals').delete().eq('id',deletingId).eq('user_id',user.id);if(error)return toast(error.message,'error');closeDelete();toast('Meta excluída.');await load()}
function bind(){$('#goalsPage')?.addEventListener('click',e=>{const n=e.target.closest('[data-goal-new]');if(n)return openGoal();const ed=e.target.closest('[data-goal-edit]');if(ed)return openGoal(ed.dataset.goalEdit);const ad=e.target.closest('[data-goal-add]');if(ad)return openContribution(ad.dataset.goalAdd);const tg=e.target.closest('[data-goal-toggle]');if(tg)return toggleGoal(tg.dataset.goalToggle);const dl=e.target.closest('[data-goal-delete]');if(dl)return openDelete(dl.dataset.goalDelete)});$('#goalForm')?.addEventListener('submit',saveGoal);$('#goalContributionForm')?.addEventListener('submit',addContribution);$('#confirmGoalDelete')?.addEventListener('click',confirmDelete);document.querySelectorAll('[data-close-goal]').forEach(x=>x.addEventListener('click',closeGoal));document.querySelectorAll('[data-close-goal-contribution]').forEach(x=>x.addEventListener('click',closeContribution));document.querySelectorAll('[data-close-goal-delete]').forEach(x=>x.addEventListener('click',closeDelete))}
ensureStyles();ensureUI();bind();const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;if(user)await load();supabase.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;if(user)setTimeout(load,0);else{goals=[];render()}});

// Carrega a IA Financeira, planos, acessos, checkout e Indique & Evolua pela versão atual do produto.
import('./ai-module.js?v=20260913-0090').catch(error=>console.error('Falha ao carregar IA Financeira',error));